"""Synology API Python Client."""
from . import \
    audiostation, \
    async_client, \
    auth, \
    base_api, \
    chat, \
    cloud_sync, \
    calendar, \
    core_active_backup, \
    core_backup, \
    core_certificate, \
    core_directory, \
    core_directory_service_check, \
    core_external_device, \
    core_group, \
    core_iscsi, \
    core_network, \
    core_notification, \
    core_package, \
    core_security, \
    core_security_auth, \
    core_service_apps, \
    core_service_hw, \
    core_service_user, \
    core_share, \
    core_storage, \
    core_sys_info, \
    core_system, \
    core_upgrade, \
    core_user, \
    dhcp_server, \
    directory_server, \
    docker_api, \
    downloadstation, \
    drive_admin_console, \
    filestation, \
    ldap_server, \
    log_center, \
    notestation, \
    oauth, \
    photos, \
    security_advisor, \
    snapshot, \
    surveillancestation, \
    universal_search, \
    usb_copy, \
    virtualization, \
    vpn
