name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build Docs
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install Python dependencies
        run: pip install -r requirements.txt

      - name: Generate API docs markdown
        run: python3 -m scripts.docs_parser -a -l

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm
          cache-dependency-path: ./documentation/package-lock.json

      - name: Install Node dependencies
        run: npm ci
        working-directory: ./documentation

      - name: Build Docusaurus website
        run: npm run build
        working-directory: ./documentation

      - name: Upload Build Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./documentation/build

  deploy:
    name: Deploy to GitHub Pages
    needs: build

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
