name: pre-commit

concurrency:
  group: pre-commit-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
  push:
    branches: [main]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Cache asdf
      uses: actions/cache@v4
      with:
        path: |
          ~/.asdf
        key: ${{ runner.os }}-asdf-${{ hashFiles('.tool-versions') }}
        restore-keys: |
          ${{ runner.os }}-asdf-
    - uses: asdf-vm/actions/install@v4
    - uses: pre-commit/action@v3.0.1
#      env:
#        SKIP: hook-id-to-skip
